name : Koak
on :
  push :
    branches :
      - master
      - main
      - dev

jobs :
  unit-test :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout repo
        uses : actions/checkout@v2
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Install llvm
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y llvm-9-dev
      - name : Run unit test
        run : stack test --allow-different-user --coverage > unit_test_output
      - name : Upload file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_output
          path: unit_test_output